---
title: "Prep data for longitudinal study forecasting app"
author: "Michelle.VanTieghem"
date: "June 12, 2020"
output:
  html_document:
    number_sections: no
    df_print: kable
    code_folding: show
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
      
---


## README
prep BEES Lab COPE data files for input into shiny app.

```{r, echo = F, warning = F, include = F}
library(tidyverse)
library(lubridate) # for date calculations
# for age function
source("custom_functions.R")
set.seed(333) # for random sampling
```

```{r, echo = F}
# note: inputs are not RAW data. 
# inputs are merged / cleaned data.
baseline_clean <- read.csv("../../cope_data_dashboard/clean_data/cleaned_baseline_survey_2020-07-14.csv")
preg_clean <-  read.csv("../../cope_data_dashboard/clean_data/cleaned_preg_survey_2020-07-14.csv")
newmom_clean <- read.csv("../../cope_data_dashboard/clean_data/cleaned_new_mom_survey_2020-07-14.csv")
```


## 1. pregnant women

```{r}
preg_clean <- preg_clean %>% 
  mutate(child_birth_date = ymd(pregnant_due_date), 
         survey_date = ymd(today_date)) %>%
  select(record_id, survey_date, child_birth_date)

```



## 2. new moms
```{r}
# new mom, some of which includes women pregnant at baseline
newmom_clean <- newmom_clean %>%
  filter( !is.na(child_birth_date)) %>%
  # calculate child age in months, based on TODAY's date.
  mutate(child_birth_date = ymd(child_birth_date), 
         survey_date = ymd(new_mom_survey_date)) %>%
  select(record_id, survey_date, child_birth_date)
```

 find those who we know from follow up gave birth already, 
 so they aren't counted twice - and remove them from the pregnant list
```{r}
preg2 <- preg_clean %>%
  filter(!record_id %in% newmom_clean$record_id) 

nrow(preg_clean) - nrow(preg2)
```

## 3. get demographic variables 
```{r}
demo <- baseline_clean %>%
  mutate(enrollment_date = ymd(baseline_date)) %>%
  select(record_id, enrollment_date, median_income, white, hispanic)

head(demo)
```


## 4 combine and save for shiny app input.
```{r}
mom_surveys <- rbind(newmom_clean, preg2)

enrolled <- demo %>%
  left_join(., mom_surveys, by = "record_id", all = T) %>%
  # reformat these variables
  mutate(demo_variable2 = ifelse(white == 1, "White", "Other"), 
         demo_variable3 = ifelse(hispanic == 1, "Hispanic", "Not Hispanic")) %>%
  rename(demo_variable1 = median_income) %>%
  select(-white, -hispanic)

head(enrolled)
```

## check data
```{r}
write.csv(enrolled, "../data/test_enrolled_for_study_forecast.csv", row.names = F)
```
